use crate::{config::Paths, registry::App};

pub fn environment(a: &App, paths: &Paths) -> String {
    format!("# Generated by celld-ctl; node credentials remain in node.env.\nCELLD_BIN={}/v{}/celld\nCELLD_BUCKET={}\nS3_ENDPOINT={}\nAWS_REGION={}\nCELLD_ADDR=127.0.0.1:{}\nCELLD_INTERNAL_ADDR=127.0.0.1:{}\nCELLD_WATCH={}/{}\nCELLD_TRUST_FORWARDED_HEADERS=1\n", paths.releases.display(),a.target.celld_version,a.target.bucket,a.target.endpoint,a.target.region,a.port,a.internal_port,paths.app_state.display(),a.target.slug)
}

/// An exact executable path in a drop-in pins each instance, including the legacy unit.
pub fn unit_override(a: &App, paths: &Paths) -> String {
    format!("# Generated by celld-ctl\n[Service]\nLogNamespace=celld\nEnvironmentFile=\nEnvironmentFile={}\nEnvironmentFile={}/{}.env\nExecStart=\nExecStart={}/v{}/celld --listen 127.0.0.1:{} --internal-listen 127.0.0.1:{} --advertise 127.0.0.1:{} --trust-forwarded-headers\n", paths.credentials.display(), paths.cells.display(), a.target.slug, paths.releases.display(),a.target.celld_version,a.port,a.internal_port,a.internal_port)
}

pub fn caddy(apps: &[App], paths: &Paths) -> String {
    let mut s = String::from("# Generated by celld-ctl. Do not edit.\n{\n  admin 127.0.0.1:2019\n}\n:8000 {\n  map {http.request.header.X-Forwarded-Proto} {upstream_proto} {\n    default http\n    https https\n    http http\n  }\n  map {http.request.header.X-Forwarded-Host} {upstream_host} {\n    default {http.request.header.X-Forwarded-Host}\n    \"\" {http.request.host}\n  }\n  @index path /\n  handle @index {\n");
    s.push_str(&format!(
        "    root * {}\n    rewrite * /index.html\n    file_server\n  }}\n",
        paths.public.display()
    ));
    for a in apps.iter().filter(|a| a.target.enabled) {
        s.push_str(&format!("  redir /{0} /{0}/ 308\n  handle /{0}/* {{\n    reverse_proxy 127.0.0.1:{1} {{\n      header_up X-Forwarded-Proto {{upstream_proto}}\n      header_up X-Forwarded-Host {{upstream_host}}\n    }}\n  }}\n", a.target.slug,a.port));
    }
    s.push_str("  handle {\n    respond \"Not found\" 404\n  }\n}\n");
    s
}
fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}
pub fn html(apps: &[App]) -> String {
    let mut s = String::from("<!doctype html><html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><title>Applications</title><style>body{font:16px system-ui;max-width:60em;margin:3em auto;padding:1em}td,th{padding:.6em;text-align:left}table{border-collapse:collapse}tr{border-bottom:1px solid #ddd}</style><h1>Applications</h1><p>Read-only registry snapshot. Published means readiness was verified at activation, not a live health guarantee.</p><table><tr><th>Application</th><th>Route</th><th>celld</th><th>Deployment</th></tr>");
    for a in apps {
        let slug = escape(&a.target.slug);
        let label = if a.target.enabled {
            format!("<a href=\"/{slug}/\">{slug}</a>")
        } else {
            slug
        };
        s.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            label,
            if a.target.enabled {
                "Published"
            } else {
                "Disabled"
            },
            escape(&a.target.celld_version),
            escape(a.version_id.as_deref().unwrap_or("Not deployed"))
        ));
    }
    s.push_str("</table></html>\n");
    s
}
